In [9]:
import numpy as np
import numpy.random as nr
from sklearn.linear_model import LinearRegression


In [3]:


# Number of pilot symbols
N = 100
PSNR_dB = 20
PSNR = 10**(PSNR_dB/10)

In [6]:
# Complex pilot symbols (normalized)
x_real = 2*nr.randint(2,size=N) - 1
x_imag = 2*nr.randint(2,size=N) - 1
x = np.sqrt(PSNR)*(x_real + 1j*x_imag)
x

array([ 10.-10.j, -10.+10.j,  10.-10.j,  10.+10.j, -10.+10.j,  10.+10.j,
       -10.+10.j, -10.-10.j, -10.+10.j,  10.+10.j,  10.+10.j,  10.-10.j,
        10.+10.j, -10.+10.j, -10.+10.j,  10.+10.j, -10.+10.j, -10.+10.j,
        10.-10.j,  10.+10.j,  10.+10.j, -10.+10.j,  10.-10.j, -10.+10.j,
       -10.+10.j,  10.+10.j,  10.+10.j,  10.-10.j,  10.-10.j, -10.+10.j,
       -10.-10.j, -10.+10.j, -10.+10.j,  10.+10.j, -10.+10.j, -10.+10.j,
        10.-10.j,  10.+10.j,  10.+10.j, -10.-10.j, -10.+10.j,  10.-10.j,
        10.+10.j, -10.+10.j, -10.-10.j, -10.-10.j,  10.+10.j, -10.-10.j,
        10.-10.j, -10.+10.j,  10.+10.j, -10.-10.j, -10.+10.j,  10.+10.j,
       -10.-10.j,  10.+10.j, -10.-10.j,  10.-10.j,  10.-10.j, -10.-10.j,
       -10.+10.j, -10.+10.j,  10.-10.j, -10.-10.j, -10.-10.j, -10.+10.j,
        10.+10.j,  10.+10.j, -10.+10.j, -10.-10.j,  10.+10.j,  10.-10.j,
        10.-10.j, -10.+10.j, -10.+10.j,  10.+10.j, -10.-10.j, -10.+10.j,
        10.+10.j, -10.+10.j, -10.+10.j,  10.+10.j, 

In [7]:
# True complex channel
h_true = 1.2 + 0.7j

# Complex AWGN
noise = (nr.randn(N) + 1j*nr.randn(N))/np.sqrt(2)
noise

array([ 0.26538334-0.0568142j , -0.23828377-0.12517251j,
        1.05476784+1.11213724j,  1.30665776-0.25246532j,
        0.57330574-0.04929703j,  0.71133506-1.29172507j,
       -0.33322511+0.04971419j,  0.21801526-0.64463547j,
       -0.45785414-0.06133823j, -0.12036646+0.15364943j,
       -0.0850043 +0.18323013j, -0.69582955-0.23584745j,
       -0.39722316-0.43026725j, -0.91786184-0.43019354j,
        0.25958956-0.29851592j,  2.13227105-0.77207304j,
        1.11063722-0.65993531j, -0.11789122+0.54474551j,
        0.75017008+1.68156463j, -0.30318417-0.26857188j,
        0.12964251-0.87224698j,  0.03034935-0.17136275j,
        1.47412325+0.36733716j, -0.70020205-0.15969606j,
        1.18221055+1.34381528j, -0.84435382+0.00421816j,
       -0.04389111-0.91116736j, -0.95359834+0.57108764j,
       -1.35795182-0.18449405j, -0.59354583+0.3925486j ,
        0.31812445-0.59589537j,  0.5258723 +0.53748839j,
        0.08830951-0.57079202j, -0.70971088+1.18019514j,
        0.38227888-0.48598025j,

In [8]:
# Recieved signal
y = h_true*x + noise

# Convert to real-valued regression
X1 = np.column_stack((np.real(x), -np.imag(x)))
X2 = np.column_stack((np.imag(x),  np.real(x)))

X = np.vstack((X1, X2))
y_stack = np.hstack((np.real(y), np.imag(y)))
y_stack

array([ 19.26538334, -19.23828377,  20.05476784,   6.30665776,
       -18.42669426,   5.71133506, -19.33322511,  -4.78198474,
       -19.45785414,   4.87963354,   4.9149957 ,  18.30417045,
         4.60277684, -19.91786184, -18.74041044,   7.13227105,
       -17.88936278, -19.11789122,  19.75017008,   4.69681583,
         5.12964251, -18.96965065,  20.47412325, -19.70020205,
       -17.81778945,   4.15564618,   4.95610889,  18.04640166,
        17.64204818, -19.59354583,  -4.68187555, -18.4741277 ,
       -18.91169049,   4.29028912, -18.61772112, -17.97229668,
        18.3865623 ,   4.50287146,   5.22919746,  -5.30612628,
       -20.01788836,  19.72348935,   6.58068725, -19.15580913,
        -3.32793739,  -4.69455706,   5.96127677,  -5.43792706,
        18.63208179, -18.25109581,   4.68564805,  -4.24773004,
       -19.45015662,   6.43236464,  -4.74929676,   4.968062  ,
        -5.38076945,  18.82564288,  18.68740662,  -4.17826138,
       -20.16782752, -18.15839175,  18.54119023,  -4.63

Linear Regression

In [2]:
model = LinearRegression(fit_intercept=False)
model.fit(X, y_stack)

# Estimated channel
h_est = model.coef_[0] + 1j * model.coef_[1]

print("True channel h   :", h_true)
print("Estimated channel:", h_est)
print("Estimation error :", np.abs(h_true - h_est)**2)


True channel h   : (1.2+0.7j)
Estimated channel: (1.1935785017099678+0.7004804009845516j)
Estimation error : 4.146642539484378e-05
